### ISSUE TITLE
`export = classNames` is getting TS error

### ISSUE THREAD

**Issue by donysukardi** [activeguild/vite-plugin-sass-dts#65]
hi, i'm getting the following error after upgrading to the latest plugin version.

```
An export assignment cannot be used in a module with other exported elements.
```

This might have been broken by the fix for https://github.com/activeguild/vite-plugin-sass-dts/issues/60.

Here's a playground with the issue: https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF0dNaByUAtiGgFzwDeAUAJBxTCoQCe8ADlAOYjkDkH3XgG5aVAL4iQADzZIYWALzYouAsTSSZcrBmZsEAYRz4iJeAtoAfePy4hhVIA.

The fix might be to export the definition differently according to export type, i.e. default or named

**Comment by donysukardi** [comment]
Oddly the error isn't observed when `skipLibCheck: true` in tsconfig.json

**Comment by activeguild** [comment]
@donysukardi 

Thank you for the issue.

It seems that exporting elsewhere when using export substitution is not a good idea.
https://github.com/activeguild/vite-plugin-sass-dts/blob/c49b1167cede5a04dc05b5ebd90a4efed74747a7/example/react-sass/src/App.module.scss.d.ts#L9-L14

I will modify the code so that it is removed since it is an unnecessary type declaration.

**Comment by activeguild** [comment]
@donysukardi 

Should be fixed in with!

```
"vite-plugin-sass-dts": "^1.2.10"
```

Thanks for the issue!!
